# ============================================================================
# wing_planform.py  -  Fusion 360 Python API script
# Generated by Design Realization Agent for the Electric Aircraft project.
#
# !!! READ THIS BEFORE RUNNING !!!
#
# SCOPE: WING PLANFORM ONLY. No fuselage, no tail, no lift/rotor system.
#        VTOL architecture has NOT been selected by the Concurrent
#        Engineering Cluster, so any of that geometry would be a guess.
#
# NUMBERS: Taken verbatim from baseline 89 (D1 id=89,
#          version v0.1-config-draft-1785188637), "dimensions" section:
#            wingspan      = 1.25  m
#            root chord    = 0.22  m
#            tip chord     = 0.15  m
#            wing area     = 0.231 m^2   (reference only, not drawn)
#            MAC           = 0.187 m     (reference only, not drawn)
#            taper ratio   = 0.682
#            aspect ratio  = 6.76
#          Straight leading edge (sweep = 0) because no sweep angle is
#          specified anywhere real yet.
#
# !!! KNOWN-STALE SPAN — DO NOT TRUST FOR FINAL GEOMETRY !!!
#     Baseline 89's 1.25 m wingspan was derived from a PLACEHOLDER
#     "notional ~10 m GA-class reference * 1/8" that was explicitly NOT
#     a commitment. Saiyam has since decided the real target absolute
#     wingspan is 1.40 m (D1 audit-log event 117, 2026-07-29). That is
#     ~12% larger, and per CLAUDE.md every downstream number (wing area,
#     AR, wing loading, V_stall, Re, cruise power, hover bracket, mission
#     energy) must be re-derived by Configuration Synthesis Lead + Math
#     & Physics Engine — NOT hand-patched, and NOT rescaled inside this
#     script. This file uses the 1.25 m numbers as stored, and MUST be
#     REGENERATED once baseline 89 is corrected to 1.40 m.
#
# AIRFOIL: Airframe Engineer's locked airfoil is SD7003 (low-Re, per
#          baseline 89 airfoil shortlist + CLAUDE.md Wave 2 record).
#          This pass does NOT loft between real SD7003 upper/lower
#          coordinates — it extrudes a flat trapezoidal planform as a
#          thickness-less-shape stand-in. A real airfoil-profile loft
#          requires real SD7003 (x,y) coordinate data at root and tip
#          sketches, which is a follow-up task.
# ============================================================================

import adsk.core
import adsk.fusion
import adsk.cam
import traceback


# --- Real numbers from baseline 89 (see header). Do not edit here; edit
#     baseline 89 upstream and regenerate this script. ---
WINGSPAN_M   = 1.25    # full span, tip-to-tip
ROOT_CHORD_M = 0.22
TIP_CHORD_M  = 0.15
# Nominal extrusion thickness as a visual stand-in for the SD7003 section.
# NOT an aerodynamic thickness — real profile lofting is a follow-up.
PLACEHOLDER_THICKNESS_M = 0.01


def run(context):
    ui = None
    try:
        app = adsk.core.Application.get()
        ui = app.userInterface

        # Fusion 360 Python API works in centimetres internally.
        M_TO_CM = 100.0
        semi_span_cm = (WINGSPAN_M / 2.0) * M_TO_CM
        root_cm      = ROOT_CHORD_M * M_TO_CM
        tip_cm       = TIP_CHORD_M  * M_TO_CM
        thick_cm     = PLACEHOLDER_THICKNESS_M * M_TO_CM

        # New document
        doc = app.documents.add(adsk.core.DocumentTypes.FusionDesignDocumentType)
        design = app.activeProduct
        root_comp = design.rootComponent
        root_comp.name = "Wing (baseline 89, span 1.25 m — STALE, target 1.40 m)"

        # Sketch on XZ plane. Convention used here:
        #   X = chordwise (leading edge at X=0, trailing edge at +X)
        #   Z = spanwise  (centerline at Z=0, tip at Z=+semi_span)
        sketches = root_comp.sketches
        xz_plane = root_comp.xZConstructionPlane
        sketch = sketches.add(xz_plane)
        sketch.name = "Wing planform (trapezoidal, straight LE)"

        lines = sketch.sketchCurves.sketchLines

        # Trapezoidal half-planform corners (right half, Z >= 0):
        #   root LE  = (0, 0, 0)
        #   root TE  = (root_cm, 0, 0)
        #   tip  TE  = (tip_cm,  0, semi_span_cm)   -- straight LE => tip LE at X=0
        #   tip  LE  = (0, 0, semi_span_cm)
        # Sketch on XZ plane consumes (X, Z) as the sketch's 2D (x, y).
        p_root_le = adsk.core.Point3D.create(0.0,         0.0, 0.0)
        p_root_te = adsk.core.Point3D.create(root_cm,     0.0, 0.0)
        p_tip_te  = adsk.core.Point3D.create(tip_cm,      0.0, semi_span_cm)
        p_tip_le  = adsk.core.Point3D.create(0.0,         0.0, semi_span_cm)

        lines.addByTwoPoints(p_root_le, p_root_te)   # root chord
        lines.addByTwoPoints(p_root_te, p_tip_te)    # trailing edge (tapered)
        lines.addByTwoPoints(p_tip_te,  p_tip_le)    # tip chord
        lines.addByTwoPoints(p_tip_le,  p_root_le)   # leading edge (straight)

        # Extrude the half-planform a small placeholder thickness.
        # This is NOT an airfoil — it is a flat trapezoidal solid so that
        # the planform is visible/measurable in 3D. Real SD7003 lofting is
        # a follow-up (needs real coordinate data).
        prof = sketch.profiles.item(0)
        extrudes = root_comp.features.extrudeFeatures
        ext_input = extrudes.createInput(
            prof, adsk.fusion.FeatureOperations.NewBodyFeatureOperation)
        distance = adsk.core.ValueInput.createByReal(thick_cm)
        ext_input.setDistanceExtent(False, distance)
        ext_feature = extrudes.add(ext_input)

        half_body = ext_feature.bodies.item(0)
        half_body.name = "Wing half (starboard)"

        # Mirror the half wing across the XY plane (Z=0 centerline) to
        # produce the full wing. Symmetry is assumed because there is no
        # decision anywhere real that specifies asymmetric geometry.
        mirror_features = root_comp.features.mirrorFeatures
        input_entities = adsk.core.ObjectCollection.create()
        input_entities.add(half_body)
        mirror_input = mirror_features.createInput(
            input_entities, root_comp.xYConstructionPlane)
        mirror_features.add(mirror_input)

        if ui:
            ui.messageBox(
                "Wing planform generated from baseline 89.\n"
                "Span = 1.25 m (STALE — real target 1.40 m, event 117).\n"
                "Root chord = 0.22 m, tip chord = 0.15 m.\n"
                "Flat extrusion stand-in; SD7003 loft is a follow-up."
            )

    except:
        if ui:
            ui.messageBox('Failed:\n{}'.format(traceback.format_exc()))
